[[Dbus]]
arch = "armv7l"
git-tree-sha1 = "eaff5a0363dedcb35e68ed91a5bcde0a98876031"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "8ca9fb0a7bda43422d102e36fb8a081ba34724767151ea876d42e7098500cb16"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.arm-linux-gnueabihf.tar.gz"
[[Dbus]]
arch = "aarch64"
git-tree-sha1 = "423854b19e9bafe27ddcedf217f5a3c1af1dbec1"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "7a887ef25cbc632a45148fc1827384bbbcd748ffcc77b8b0ab0c1346d86bb9cd"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.aarch64-linux-musl.tar.gz"
[[Dbus]]
arch = "i686"
git-tree-sha1 = "bcb9849b1c282282525332880930de863514a76f"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "f70f16b0f259c25d5b156097bc5d26896cf31c0f350021f5dd79ad60ae1a699b"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.i686-linux-musl.tar.gz"
[[Dbus]]
arch = "i686"
git-tree-sha1 = "943844a53472266d689a6e24e28b7f5f0f2beb34"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "1a26adfa11a699f5b16de78929e66b3ec83f4e757488ba2f719d95362a73cacf"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.i686-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "a765f56d629178810c1cefeaf317b251a6975e72"
os = "freebsd"

    [[Dbus.download]]
    sha256 = "3631056cc889f774a9b99b91cedc02cbff823db569bf3644de3b013b17735f5b"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.x86_64-unknown-freebsd11.1.tar.gz"
[[Dbus]]
arch = "powerpc64le"
git-tree-sha1 = "fe4304caf83167ec5e7ac6f4a05aa36ccc9b2c22"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "431919aa97ef8ad1df36ba581ed578b94f68ccc24ad86161856d86d4b0bab543"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.powerpc64le-linux-gnu.tar.gz"
[[Dbus]]
arch = "armv7l"
git-tree-sha1 = "f710145735d6b3b336a6d430da2d359c2df0d963"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "6485e9e288b791d890ef9565e51d0c900efcdf9762a71d0a5f8e5c14a7f9cb1c"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.arm-linux-musleabihf.tar.gz"
[[Dbus]]
arch = "aarch64"
git-tree-sha1 = "4aec0b0104ec8984c243f577a83a1579087cb1fd"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "54dbf3647473561525556c6457c0435375e4d656e846369a5ce05967ea48e4fc"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.aarch64-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "aff573def2b73fe2af6dc454875aa5e7437219fa"
libc = "glibc"
os = "linux"

    [[Dbus.download]]
    sha256 = "f9f50836b137d61e41127087df025d1f8a88cbb9e6119ee612428c0d5b212835"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.x86_64-linux-gnu.tar.gz"
[[Dbus]]
arch = "x86_64"
git-tree-sha1 = "91b8f46673f0f4ef3596d46af4fd2a72056d72e4"
libc = "musl"
os = "linux"

    [[Dbus.download]]
    sha256 = "eff9e38a682d7df2a8a031e497b801e828d47e63d7aadc08a96f124d89eaf8c3"
    url = "https://github.com/JuliaBinaryWrappers/Dbus_jll.jl/releases/download/Dbus-v1.12.16+0/Dbus.v1.12.16.x86_64-linux-musl.tar.gz"
